//
// ZWaveAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ZWaveAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getLightingSummary(completion: @escaping ((_ data: LightingSummary?,_ error: Error?) -> Void)) {
        getLightingSummaryWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /lightingSummary
     - 

     - examples: [{contentType=application/json, example={
  "zoneStatus" : [ {
    "level" : 6,
    "lastUpdate" : "2000-01-23T04:56:07.000+00:00",
    "name" : "name",
    "id" : "id"
  }, {
    "level" : 6,
    "lastUpdate" : "2000-01-23T04:56:07.000+00:00",
    "name" : "name",
    "id" : "id"
  } ],
  "zones" : [ {
    "deviceType" : "dimmer",
    "zone" : "zone",
    "name" : "name",
    "id" : "id",
    "deviceId" : 0
  }, {
    "deviceType" : "dimmer",
    "zone" : "zone",
    "name" : "name",
    "id" : "id",
    "deviceId" : 0
  } ]
}}]

     - returns: RequestBuilder<LightingSummary> 
     */
    open class func getLightingSummaryWithRequestBuilder() -> RequestBuilder<LightingSummary> {
        let path = "/lightingSummary"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<LightingSummary>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter deviceId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getSwitchState(deviceId: String, completion: @escaping ((_ data: DeviceState?,_ error: Error?) -> Void)) {
        getSwitchStateWithRequestBuilder(deviceId: deviceId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /lighting/switches/{deviceId}
     - 

     - examples: [{contentType=application/json, example={
  "level" : 0,
  "lastUpdate" : "2000-01-23T04:56:07.000+00:00",
  "name" : "name",
  "id" : "id"
}}]
     - parameter deviceId: (path)  

     - returns: RequestBuilder<DeviceState> 
     */
    open class func getSwitchStateWithRequestBuilder(deviceId: String) -> RequestBuilder<DeviceState> {
        var path = "/lighting/switches/{deviceId}"
        let deviceIdPreEscape = "\(deviceId)"
        let deviceIdPostEscape = deviceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{deviceId}", with: deviceIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<DeviceState>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter deviceId: (path)  
     - parameter value: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func setDimmer(deviceId: String, value: Int, completion: @escaping ((_ data: ApiResponse?,_ error: Error?) -> Void)) {
        setDimmerWithRequestBuilder(deviceId: deviceId, value: value).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /lighting/dimmers/{deviceId}/{value}
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "everything is ok"
}}]
     - parameter deviceId: (path)  
     - parameter value: (path)  

     - returns: RequestBuilder<ApiResponse> 
     */
    open class func setDimmerWithRequestBuilder(deviceId: String, value: Int) -> RequestBuilder<ApiResponse> {
        var path = "/lighting/dimmers/{deviceId}/{value}"
        let deviceIdPreEscape = "\(deviceId)"
        let deviceIdPostEscape = deviceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{deviceId}", with: deviceIdPostEscape, options: .literal, range: nil)
        let valuePreEscape = "\(value)"
        let valuePostEscape = valuePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{value}", with: valuePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApiResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     * enum for parameter units
     */
    public enum Units_setDimmerTimer: String { 
        case seconds = "seconds"
        case minutes = "minutes"
        case milliseconds = "milliseconds"
    }

    /**

     - parameter deviceId: (path)  
     - parameter value: (path)  
     - parameter timeunit: (path)  
     - parameter units: (query)  (optional, default to milliseconds)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func setDimmerTimer(deviceId: String, value: Int, timeunit: Int, units: Units_setDimmerTimer? = nil, completion: @escaping ((_ data: ApiResponse?,_ error: Error?) -> Void)) {
        setDimmerTimerWithRequestBuilder(deviceId: deviceId, value: value, timeunit: timeunit, units: units).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /lighting/dimmers/{deviceId}/{value}/timer/{timeunit}

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "everything is ok"
}}]
     - parameter deviceId: (path)  
     - parameter value: (path)  
     - parameter timeunit: (path)  
     - parameter units: (query)  (optional, default to milliseconds)

     - returns: RequestBuilder<ApiResponse> 
     */
    open class func setDimmerTimerWithRequestBuilder(deviceId: String, value: Int, timeunit: Int, units: Units_setDimmerTimer? = nil) -> RequestBuilder<ApiResponse> {
        var path = "/lighting/dimmers/{deviceId}/{value}/timer/{timeunit}"
        let deviceIdPreEscape = "\(deviceId)"
        let deviceIdPostEscape = deviceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{deviceId}", with: deviceIdPostEscape, options: .literal, range: nil)
        let valuePreEscape = "\(value)"
        let valuePostEscape = valuePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{value}", with: valuePostEscape, options: .literal, range: nil)
        let timeunitPreEscape = "\(timeunit)"
        let timeunitPostEscape = timeunitPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{timeunit}", with: timeunitPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "units": units?.rawValue
        ])


        let requestBuilder: RequestBuilder<ApiResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     * enum for parameter value
     */
    public enum Value_setSwitch: String { 
        case _true = "true"
        case _false = "false"
    }

    /**

     - parameter deviceId: (path)  
     - parameter value: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func setSwitch(deviceId: String, value: Value_setSwitch, completion: @escaping ((_ data: ApiResponse?,_ error: Error?) -> Void)) {
        setSwitchWithRequestBuilder(deviceId: deviceId, value: value).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /lighting/switches/{deviceId}/{value}
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "everything is ok"
}}]
     - parameter deviceId: (path)  
     - parameter value: (path)  

     - returns: RequestBuilder<ApiResponse> 
     */
    open class func setSwitchWithRequestBuilder(deviceId: String, value: Value_setSwitch) -> RequestBuilder<ApiResponse> {
        var path = "/lighting/switches/{deviceId}/{value}"
        let deviceIdPreEscape = "\(deviceId)"
        let deviceIdPostEscape = deviceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{deviceId}", with: deviceIdPostEscape, options: .literal, range: nil)
        let valuePreEscape = "\(value.rawValue)"
        let valuePostEscape = valuePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{value}", with: valuePostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApiResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     * enum for parameter value
     */
    public enum Value_setSwitchTimer: String { 
        case _true = "true"
        case _false = "false"
    }

    /**

     - parameter deviceId: (path)  
     - parameter value: (path)  
     - parameter minutes: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func setSwitchTimer(deviceId: String, value: Value_setSwitchTimer, minutes: Int, completion: @escaping ((_ data: ApiResponse?,_ error: Error?) -> Void)) {
        setSwitchTimerWithRequestBuilder(deviceId: deviceId, value: value, minutes: minutes).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /lighting/switches/{deviceId}/{value}/timer/{minutes}

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "everything is ok"
}}]
     - parameter deviceId: (path)  
     - parameter value: (path)  
     - parameter minutes: (path)  

     - returns: RequestBuilder<ApiResponse> 
     */
    open class func setSwitchTimerWithRequestBuilder(deviceId: String, value: Value_setSwitchTimer, minutes: Int) -> RequestBuilder<ApiResponse> {
        var path = "/lighting/switches/{deviceId}/{value}/timer/{minutes}"
        let deviceIdPreEscape = "\(deviceId)"
        let deviceIdPostEscape = deviceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{deviceId}", with: deviceIdPostEscape, options: .literal, range: nil)
        let valuePreEscape = "\(value.rawValue)"
        let valuePostEscape = valuePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{value}", with: valuePostEscape, options: .literal, range: nil)
        let minutesPreEscape = "\(minutes)"
        let minutesPostEscape = minutesPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{minutes}", with: minutesPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApiResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
