//
// City.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct City: Codable {

    public var _id: Int64?
    public var name: String?
    public var lat: Double?
    public var lon: Double?
    public var country: String?

    public init(_id: Int64? = nil, name: String? = nil, lat: Double? = nil, lon: Double? = nil, country: String? = nil) {
        self._id = _id
        self.name = name
        self.lat = lat
        self.lon = lon
        self.country = country
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case lat
        case lon
        case country
    }

}
