//
// DeviceRegistrationInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceRegistrationInfo: Codable {

    public var uri: String?
    public var _id: UUID?

    public init(uri: String? = nil, _id: UUID? = nil) {
        self.uri = uri
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case uri
        case _id = "id"
    }

}
