//
// ForecastTemperature.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ForecastTemperature: Codable {

    public var low: Double?
    public var high: Double?
    public var morning: Double?
    public var day: Double?
    public var evening: Double?
    public var night: Double?

    public init(low: Double? = nil, high: Double? = nil, morning: Double? = nil, day: Double? = nil, evening: Double? = nil, night: Double? = nil) {
        self.low = low
        self.high = high
        self.morning = morning
        self.day = day
        self.evening = evening
        self.night = night
    }


}
