//
// LightingZoneStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** the status of the lighting zone. */

public struct LightingZoneStatus: Codable {

    public var _id: String?
    public var name: String?
    public var lastUpdate: Date?
    public var level: Int?

    public init(_id: String? = nil, name: String? = nil, lastUpdate: Date? = nil, level: Int? = nil) {
        self._id = _id
        self.name = name
        self.lastUpdate = lastUpdate
        self.level = level
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case lastUpdate
        case level
    }

}
