//
// LightingZone.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LightingZone: Codable {

    public enum DeviceType: String, Codable { 
        case dimmer = "dimmer"
        case _switch = "switch"
    }
    public var _id: String?
    public var name: String?
    public var deviceId: Int?
    public var deviceType: DeviceType?
    public var zone: String?

    public init(_id: String? = nil, name: String? = nil, deviceId: Int? = nil, deviceType: DeviceType? = nil, zone: String? = nil) {
        self._id = _id
        self.name = name
        self.deviceId = deviceId
        self.deviceType = deviceType
        self.zone = zone
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case deviceId
        case deviceType
        case zone
    }

}
