//
// TemperatueZoneStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** status of a single zone */

public struct TemperatueZoneStatus: Codable {

    public enum Units: String, Codable { 
        case celsius = "celsius"
        case fahrenheit = "fahrenheit"
    }
    /** the unique identifier for the zone */
    public var _id: String
    /** the name of the zone */
    public var name: String?
    /** the temperature in the zone */
    public var value: Double
    /** the temperature units */
    public var units: Units?
    /** the timestamp when the temperature was measured */
    public var timestamp: Date

    public init(_id: String, name: String? = nil, value: Double, units: Units? = nil, timestamp: Date) {
        self._id = _id
        self.name = name
        self.value = value
        self.units = units
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case value
        case units
        case timestamp
    }

}
